import Head from 'next/head';
import React, { FC, ReactNode } from 'react';
import { Navbar } from '../Navbar';
import styles from './MainLayout.module.css';

export interface IMainLayoutProps{
  children:ReactNode;
}
export const MainLayout: FC<IMainLayoutProps> = (props):JSX.Element => {
  const {children}= props;
  return (
    <div className={styles.container}>
        <Head>
            <title>Ruben´s site</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <main className={styles.main}>
            {children}
        </main>
    </div>
  )
}
